// specific error handling in catch block, can be used to encounter specific scenarios

export function handleError(error: Error, res: Response) {}
